name: Train Model

on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0
          pip install pandas
          pip install scikit-learn

      - name: Run Training
        run: |
          cd MLProject
          python modelling.py